// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knwdjeicyisqsfiisaic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtud2RqZWljeWlzcXNmaWlzYWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2OTA0NTAsImV4cCI6MjA5MTI2NjQ1MH0.ZuojkfCS_2K-2WnL-BjNGjlLPX0GfKLDmaFjOvkAoEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});